/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import entidades.Materia;
import java.awt.event.ItemEvent;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lucap
 */
public class ManejoInscripciones extends javax.swing.JInternalFrame {

  private final DefaultTableModel model = new DefaultTableModel();

  /**
   * Creates new form ManejoInscripciones
   */
  public ManejoInscripciones() {
    initComponents();
    initTabla();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    radioButtons = new javax.swing.ButtonGroup();
    formularioDeInscripcion = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    jSeparator1 = new javax.swing.JSeparator();
    jLabel1 = new javax.swing.JLabel();
    alumnos = new javax.swing.JComboBox<>();
    listadoDeMaterias = new javax.swing.JPanel();
    titulo = new javax.swing.JLabel();
    jRadioButton1 = new javax.swing.JRadioButton();
    jRadioButton2 = new javax.swing.JRadioButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    tabla = new javax.swing.JTable();
    botones = new javax.swing.JPanel();
    jButton1 = new javax.swing.JButton();
    filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
    jButton2 = new javax.swing.JButton();
    filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
    jButton3 = new javax.swing.JButton();

    setClosable(true);

    jLabel2.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel2.setText("Formulario de Inscripcion");

    jLabel1.setText("Seleccione un alumno:");

    alumnos.setModel(new javax.swing.DefaultComboBoxModel<>(new accesoDeDatos.AlumnoData().listarAlumnos().toArray(new entidades.Alumno[0])));
    alumnos.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        alumnosItemStateChanged(evt);
      }
    });

    javax.swing.GroupLayout formularioDeInscripcionLayout = new javax.swing.GroupLayout(formularioDeInscripcion);
    formularioDeInscripcion.setLayout(formularioDeInscripcionLayout);
    formularioDeInscripcionLayout.setHorizontalGroup(
      formularioDeInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(formularioDeInscripcionLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(formularioDeInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(formularioDeInscripcionLayout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(jLabel2)
            .addGap(0, 0, Short.MAX_VALUE))
          .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(formularioDeInscripcionLayout.createSequentialGroup()
            .addComponent(jLabel1)
            .addGap(102, 102, 102)
            .addComponent(alumnos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        .addContainerGap())
    );
    formularioDeInscripcionLayout.setVerticalGroup(
      formularioDeInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(formularioDeInscripcionLayout.createSequentialGroup()
        .addGap(10, 10, 10)
        .addComponent(jLabel2)
        .addGap(5, 5, 5)
        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addGroup(formularioDeInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(alumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    titulo.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
    titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    titulo.setText("Listado de Materias");

    radioButtons.add(jRadioButton1);
    jRadioButton1.setText("materias inscriptas");
    jRadioButton1.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        listarMateriasInscriptas(evt);
      }
    });

    radioButtons.add(jRadioButton2);
    jRadioButton2.setText("materias no inscriptas");
    jRadioButton2.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        listarMateriasNoInscriptas(evt);
      }
    });

    tabla.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String [] {
        "Title 1", "Title 2", "Title 3", "Title 4"
      }
    ));
    jScrollPane1.setViewportView(tabla);

    botones.setLayout(new javax.swing.BoxLayout(botones, javax.swing.BoxLayout.LINE_AXIS));

    jButton1.setText("Inscribir");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });
    botones.add(jButton1);
    botones.add(filler1);

    jButton2.setText("Anular Inscripcion");
    botones.add(jButton2);
    botones.add(filler2);

    jButton3.setText("Salir");
    botones.add(jButton3);

    javax.swing.GroupLayout listadoDeMateriasLayout = new javax.swing.GroupLayout(listadoDeMaterias);
    listadoDeMaterias.setLayout(listadoDeMateriasLayout);
    listadoDeMateriasLayout.setHorizontalGroup(
      listadoDeMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(listadoDeMateriasLayout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(listadoDeMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(listadoDeMateriasLayout.createSequentialGroup()
            .addComponent(jRadioButton1)
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(jRadioButton2))
          .addGroup(listadoDeMateriasLayout.createSequentialGroup()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE)))
        .addContainerGap())
      .addComponent(botones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(listadoDeMateriasLayout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(titulo)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    listadoDeMateriasLayout.setVerticalGroup(
      listadoDeMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(listadoDeMateriasLayout.createSequentialGroup()
        .addGap(10, 10, 10)
        .addComponent(titulo)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(listadoDeMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jRadioButton1)
          .addComponent(jRadioButton2))
        .addGap(18, 18, 18)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(botones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap(69, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(formularioDeInscripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(listadoDeMaterias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap(69, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(20, 20, 20)
        .addComponent(formularioDeInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(listadoDeMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(37, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jButton1ActionPerformed

  private void listarMateriasInscriptas(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_listarMateriasInscriptas
    if (evt.getStateChange() == ItemEvent.SELECTED) {
      entidades.Alumno elegido = alumnos.getItemAt(alumnos.getSelectedIndex());
      llenarTabla(new accesoDeDatos.InscripcionData().obtenerMateriasCursadas(elegido.getIdAlumno()));
    }
  }//GEN-LAST:event_listarMateriasInscriptas

  private void listarMateriasNoInscriptas(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_listarMateriasNoInscriptas
    if (evt.getStateChange() == ItemEvent.SELECTED) {
      entidades.Alumno elegido = alumnos.getItemAt(alumnos.getSelectedIndex());
      llenarTabla(new accesoDeDatos.InscripcionData().obtenerNOMateriasCursadas(elegido.getIdAlumno()));
    }
  }//GEN-LAST:event_listarMateriasNoInscriptas

  private void alumnosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_alumnosItemStateChanged
    radioButtons.clearSelection();
    limpiarTabla();
  }//GEN-LAST:event_alumnosItemStateChanged

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JComboBox<entidades.Alumno> alumnos;
  private javax.swing.JPanel botones;
  private javax.swing.Box.Filler filler1;
  private javax.swing.Box.Filler filler2;
  private javax.swing.JPanel formularioDeInscripcion;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton3;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JRadioButton jRadioButton1;
  private javax.swing.JRadioButton jRadioButton2;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JPanel listadoDeMaterias;
  private javax.swing.ButtonGroup radioButtons;
  private javax.swing.JTable tabla;
  private javax.swing.JLabel titulo;
  // End of variables declaration//GEN-END:variables

  private void llenarTabla(List<Materia> materias) {
    limpiarTabla();
    materias.forEach(materia -> model.addRow(materia.getData()));
  }

  private void limpiarTabla() {
    model.setRowCount(0);
  }

  private void initTabla() {
    model.addColumn("ID");
    model.addColumn("Nombre");
    model.addColumn("Año");
    tabla.setModel(model);
  }
}
